name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          MONGODB_APPNAME: ${{ secrets.MONGODB_APPNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run build

      - name: List build directory contents
        run: ls -al dist/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/master' ||
      (github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.ref == 'refs/heads/master' &&
      github.event.pull_request.merged == true)

    steps:
      - name: Create .env file
        run: |
          touch .env
          echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" > .env
          echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env
          echo "MONGODB_APPNAME=${{ secrets.MONGODB_APPNAME }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Transfer Build Folder and .env to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          target: ${{ secrets.DEPLOY_TARGET }}
          source: |
            dist/    # Use a single valid path for the dist folder
            .env     # Include the .env file

      # - name: Restart Application with PM2
      #   run: |
      #     echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
      #     chmod 600 deploy_key.pem
      #     ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
      #       pm2 restart your-app-name || pm2 start dist/main.js --name your-app-name
      #     EOF
      #     rm deploy_key.pem
